apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: conexao-solidaria
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: campaigns-api
        static_configs:
          - targets: ['campaigns-api-svc:8080']
        metrics_path: /metrics
      - job_name: donation-worker
        static_configs:
          - targets: ['donation-worker-svc:9091']
        metrics_path: /metrics
