FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app
COPY *.sln ./
COPY src/CampaignsApi/*.csproj ./src/CampaignsApi/
RUN dotnet restore
COPY . .
RUN dotnet publish src/CampaignsApi -c Release -o /publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /publish .
EXPOSE 8080
ENTRYPOINT ["dotnet", "CampaignsApi.dll"]
