apiVersion: v1
kind: ConfigMap
metadata:
  name: campaigns-api-config
  namespace: conexao-solidaria
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  ConnectionStrings__SqlServer: "Server=sqlserver-svc,1433;Database=ConexaoSolidaria;User Id=sa;Password=ConexaoSolidaria2026;TrustServerCertificate=True"
  RabbitMq__Host: "rabbitmq-svc"
  RabbitMq__Port: "5672"
  RabbitMq__Username: "guest"
  RabbitMq__Password: "guest"
  Jwt__SecretKey: "super-secret-jwt-key-for-development-only-32c"
  Jwt__Issuer: "ConexaoSolidaria"
  Jwt__Audience: "ConexaoSolidaria"
  Database__AutoMigrate: "true"
