apiVersion: v1
kind: Service
metadata:
  name: campaigns-api-svc
  namespace: conexao-solidaria
spec:
  selector:
    app: campaigns-api
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
